AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for local Lambda testing

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Runtime: python3.12
    Environment:
      Variables:
        JOBS_TABLE: DocumentJobs
        SENTENCES_TABLE: Sentences
        LLM_CALL_LOG_TABLE: LLMCallLog
        LLM_CALL_PARSED_TABLE: LLMCallExtracts
        RAW_BUCKET: !Ref RawBucket
        VERIFIED_BUCKET: !Ref VerifiedBucket
        KG_BUCKET: !Ref KGBucket
        GENERATE_ENDPOINT: http://host.docker.internal:8000
        EMBED_ENDPOINT: http://host.docker.internal:8001

Resources:
  # S3 Buckets
  RawBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: raw-documents-local

  VerifiedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: verified-documents-local

  KGBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: knowledge-graph-local

  # DynamoDB Tables
  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DocumentJobs
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  SentencesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Sentences
      AttributeDefinitions:
        - AttributeName: sentence_hash
          AttributeType: S
        - AttributeName: job_id
          AttributeType: S
      KeySchema:
        - AttributeName: sentence_hash
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ByJobId
          KeySchema:
            - AttributeName: job_id
              KeyType: HASH
            - AttributeName: sentence_hash
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  LLMLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: LLMCallLog
      AttributeDefinitions:
        - AttributeName: call_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
        - AttributeName: job_id
          AttributeType: S
        - AttributeName: sentence_hash
          AttributeType: S
      KeySchema:
        - AttributeName: call_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: ByJobId
          KeySchema:
            - AttributeName: job_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: BySentenceHash
          KeySchema:
            - AttributeName: sentence_hash
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  LLMExtractTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: LLMCallExtracts
      AttributeDefinitions:
        - AttributeName: call_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
        - AttributeName: sentence_hash
          AttributeType: S
        - AttributeName: job_id
          AttributeType: S
      KeySchema:
        - AttributeName: call_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: BySentenceHash
          KeySchema:
            - AttributeName: sentence_hash
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: ByJobId
          KeySchema:
            - AttributeName: job_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  QueriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Queries
      AttributeDefinitions:
        - AttributeName: query_id
          AttributeType: S
      KeySchema:
        - AttributeName: query_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Lambda Layer
  RequestsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: requests-layer
      ContentUri: lambda_layer/
      CompatibleRuntimes:
        - python3.12

  # Job Management Functions
  UploadHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/job_mgmt/l1_upload_handler/
      Handler: lambda_function.lambda_handler

  ValidateDoc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/job_mgmt/l2_validate_doc/
      Handler: lambda_function.lambda_handler

  SanitizeDoc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/job_mgmt/l3_sanitize_doc/
      Handler: lambda_function.lambda_handler

  ListAllDocs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/job_mgmt/l4_list_all_docs/
      Handler: lambda_function.lambda_handler

  ManualTrigger:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/job_mgmt/l1_manual_trigger/
      Handler: lambda_function.lambda_handler

  UpdateDocStatus:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/job_mgmt/l3_update_doc_status/
      Handler: lambda_function.lambda_handler

  CheckDedup:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/job_mgmt/l5_check_dedup/
      Handler: lambda_function.lambda_handler

  GetSentencesFromS3:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/job_mgmt/l8_get_sentences_from_s3/
      Handler: lambda_function.lambda_handler

  # LLM Gateway Functions
  LLMCall:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/llm_gateway/l7_llm_call/
      Handler: lambda_function.lambda_handler
      Layers:
        - !Ref RequestsLayer

  EmbeddingCall:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/llm_gateway/l8_embedding_call/
      Handler: lambda_function.lambda_handler
      Layers:
        - !Ref RequestsLayer

  # KG Agent Functions
  ExtractEntities:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/kg_agents/l9_extract_entities/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          LLM_CALL_LAMBDA_NAME: LLMCall
          SCORER_LAMBDA_NAME: ScoreExtractions

  ExtractKriya:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/kg_agents/l10_extract_kriya/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          LLM_CALL_LAMBDA_NAME: LLMCall
          SCORER_LAMBDA_NAME: ScoreExtractions

  BuildEvents:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/kg_agents/l11_build_events/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          LLM_CALL_LAMBDA_NAME: LLMCall
          SCORER_LAMBDA_NAME: ScoreExtractions

  AuditEvents:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/kg_agents/l12_audit_events/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          LLM_CALL_LAMBDA_NAME: LLMCall

  ExtractRelations:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/kg_agents/l13_extract_relations/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          LLM_CALL_LAMBDA_NAME: LLMCall

  ExtractAttributes:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/kg_agents/l14_extract_attributes/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          LLM_CALL_LAMBDA_NAME: LLMCall

  ScoreExtractions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/kg_agents/l24_score_extractions/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          LLM_CALL_LAMBDA_NAME: LLMCall

  # Graph Operations Functions
  GraphNodeOps:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/graph_ops/l15_graph_node_ops/
      Handler: lambda_function.lambda_handler
      Layers:
        - !Ref RequestsLayer

  GraphEdgeOps:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/graph_ops/l16_graph_edge_ops/
      Handler: lambda_function.lambda_handler
      Layers:
        - !Ref RequestsLayer

  # RAG Functions
  RetrieveFromEmbedding:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/rag/l17_retrieve_from_embedding/
      Handler: lambda_function.lambda_handler

  SynthesizeAnswer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/rag/l18_synthesize_answer/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          RETRIEVE_LAMBDA: RetrieveFromEmbedding

  QueryProcessor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/rag/l23_query_processor/
      Handler: lambda_function.lambda_handler
      Layers:
        - !Ref RequestsLayer
      Environment:
        Variables:
          QUERIES_TABLE: Queries
          LLM_CALL_LAMBDA_NAME: LLMCall
          RETRIEVE_LAMBDA: RetrieveFromEmbedding

  # API Tools
  QuerySubmit:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/api_tools/l21_query_submit/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          QUERIES_TABLE: Queries
          QUERY_PROCESSOR_LAMBDA: QueryProcessor

  QueryStatus:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/api_tools/l22_query_status/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          QUERIES_TABLE: Queries

  GetProcessingChain:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/api_tools/l19_get_processing_chain/
      Handler: lambda_function.lambda_handler

  GetSentenceChain:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda_src/api_tools/l20_get_sentence_chain/
      Handler: lambda_function.lambda_handler

Outputs:
  RawBucketName:
    Value: !Ref RawBucket
  VerifiedBucketName:
    Value: !Ref VerifiedBucket
  KGBucketName:
    Value: !Ref KGBucket
