import json
import sys
import os

# --- INPUT FILES ---
# The CDK output JSON file is passed as the first argument
if len(sys.argv) < 2:
    print("Usage: python scripts/parse_outputs.py <cdk-outputs-backend.json>")
    sys.exit(1)

output_file = sys.argv[1]

# Instead of frontend/.env, write directly to root .env
env_file = ".env"

# --- READ CDK OUTPUTS ---
if not os.path.exists(output_file):
    print(f"ERROR: CDK output file not found: {output_file}")
    sys.exit(1)

with open(output_file, "r") as f:
    cdk_outputs = json.load(f)

# --- LOAD EXISTING .env VARIABLES ---
env_vars = {}
if os.path.exists(env_file):
    with open(env_file, "r") as f:
        for line in f:
            if "=" in line and not line.strip().startswith("#"):
                key, val = line.strip().split("=", 1)
                env_vars[key] = val

# --- UPDATE ENV VALUES FROM CDK OUTPUTS ---

# Serverless stack outputs
if "ServerlessStack" in cdk_outputs:
    stack_outputs = cdk_outputs["ServerlessStack"]

    mappings = {
        "ApiUrl": "APP_API_GATEWAY_URL",
        "KGBucket": "APP_KG_BUCKET",
        "RawBucket": "APP_RAW_BUCKET",
        "VerifiedBucket": "APP_VERIFIED_BUCKET",
        "JobsTable": "APP_JOBS_TABLE",
        "StateMachineArn": "APP_STATE_MACHINE_ARN",
        "SentencesTableNameOutput": "APP_SENTENCES_TABLE",
        "LLMCallLogTableOutput": "APP_LLM_CALL_LOG_TABLE",
    }

    for key, env_key in mappings.items():
        if key in stack_outputs:
            env_vars[env_key] = stack_outputs[key]

# EKS stack outputs
if "EksStack" in cdk_outputs:
    stack_outputs = cdk_outputs["EksStack"]

    eks_mappings = {
        "GenerateEndpoint": "APP_GENERATE_ENDPOINT_URL",
        "EmbedEndpoint": "APP_EMBED_ENDPOINT_URL",
    }

    for key, env_key in eks_mappings.items():
        if key in stack_outputs:
            env_vars[env_key] = stack_outputs[key]

# --- WRITE UPDATED .ENV FILE ---
with open(env_file, "w") as f:
    f.write("# This file is auto-generated by deployment scripts.\n")
    for key, val in env_vars.items():
        f.write(f"{key}={val}\n")

print(f"✅ Successfully updated {env_file}")
