import json
import sys
import os

# The CDK output file is the first argument
output_file = sys.argv[1]
# The frontend env file is the second
frontend_env_file = "frontend/.env"

# Read the CDK JSON output
with open(output_file, "r") as f:
    cdk_outputs = json.load(f)

# Read the existing frontend .env file, if it exists
env_vars = {}
if os.path.exists(frontend_env_file):
    with open(frontend_env_file, "r") as f:
        for line in f:
            if "=" in line:
                key, val = line.strip().split("=", 1)
                env_vars[key] = val

# Update the values from our CDK output
# Handle ServerlessStack outputs
if "ServerlessStack" in cdk_outputs:
    stack_outputs = cdk_outputs["ServerlessStack"]

    # Map the actual output names from your CDK stack
    if "ApiUrl" in stack_outputs:
        env_vars["APP_API_GATEWAY_URL"] = stack_outputs["ApiUrl"]

    if "KGBucket" in stack_outputs:
        env_vars["APP_KG_BUCKET"] = stack_outputs["KGBucket"]

    if "RawBucket" in stack_outputs:
        env_vars["APP_RAW_BUCKET"] = stack_outputs["RawBucket"]

    if "VerifiedBucket" in stack_outputs:
        env_vars["APP_VERIFIED_BUCKET"] = stack_outputs["VerifiedBucket"]

    if "JobsTable" in stack_outputs:
        env_vars["APP_JOBS_TABLE"] = stack_outputs["JobsTable"]

    if "StateMachineArn" in stack_outputs:
        env_vars["APP_STATE_MACHINE_ARN"] = stack_outputs["StateMachineArn"]

    if "SentencesTableNameOutput" in stack_outputs:
        env_vars["APP_SENTENCES_TABLE"] = stack_outputs["SentencesTableNameOutput"]

    if "LLMCallLogTableOutput" in stack_outputs:
        env_vars["APP_LLM_CALL_LOG_TABLE"] = stack_outputs["LLMCallLogTableOutput"]

# Handle EKS stack outputs
if "EksStack" in cdk_outputs:
    stack_outputs = cdk_outputs["EksStack"]

    if "GenerateEndpoint" in stack_outputs:
        env_vars["APP_GENERATE_ENDPOINT_URL"] = stack_outputs["GenerateEndpoint"]

    if "EmbedEndpoint" in stack_outputs:
        env_vars["APP_EMBED_ENDPOINT_URL"] = stack_outputs["EmbedEndpoint"]

# Write the new/updated .env file
with open(frontend_env_file, "w") as f:
    f.write("# This file is auto-generated by deployment scripts.\n")
    for key, val in env_vars.items():
        f.write(f"{key}={val}\n")

print(f"Successfully updated {frontend_env_file}")
